### ISSUE TITLE
testResignFirstResponderAndCollapse is not independent

### ISSUE THREAD

**Issue by brockboland** [venmo/VENTokenField#42]
The `testResignFirstResponderAndCollapse` test checks that the collapsed label shows "3 people", but does not add any tokens of its own: it assumes that `testBasicFlow` has run before it. As such, this test method cannot be run independently of the full suite.

**Comment by ayanonagon** [comment]
Ah, great catch, thank you! We’ll fix it as soon as we can, but if PR’s are welcome if you’re up to it. :smile_cat:
