### ISSUE TITLE
isFirstResponder

### ISSUE THREAD

**Issue by walsh2000** [venmo/VENTokenField#49]
Hello

VENTokenField responds to become & resign firstResponder, but does not correctly respond to isFirstResponder.

Would you be open to a PR which exposes isFirstResponder ?

Something like:
````
- (BOOL)isFirstResponder {
	return [self.inputTextField isFirstResponder];
}

````

**Comment by ayanonagon** [comment]
Thanks for making the PR.

**Comment by fukemy** [comment]
Hello, did u have this function to implement in this patch? I face the problem is keyboard show when click to token
