### ISSUE TITLE
App crashing on return key tapped

### ISSUE THREAD

**Issue by jonthomp** [venmo/VENTokenField#59]
I'm using VENTokenField in a Swift project with Cocoapods.

Everything appears to be working fine, no build errors etc, until you tap the return key on the keyboard when editing a token field. At this point my whole app crashes with an error about not being able to load VENToken.xib.

```
2015-04-06 20:05:50.626 PapApp[55087:2522739] *** Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle
</Users/Jon/Library/Developer/CoreSimulator/Devices/33BD6BA7-D24D-44EE-9D74-1F98926EECAE/data/Containers/Bundle/Application/6B893A11-5345-401C-9094-C858CD37C0A4/PapApp.app>
(loaded)' with name 'VENToken''
```

**Comment by ayanonagon** [comment]
Thank you for filing this bug! This will be fixed in `v2.4.0` (to be released this evening). Thanks again. :octocat:
