### ISSUE TITLE
Example code for autocomplete gif  used in read me

### ISSUE THREAD

**Issue by jonthomp** [venmo/VENTokenField#62]
Thanks for fixing up that bug, it's working great now. Do you, or do you plan to, have a version with autocomplete functionality like in the preview gif used in the read me?

**Comment by davidbarsky** [comment]
@jonthomp I don't know the project will be updated with a sample project like the one shown in the GIF, but you can use the `tokenField:didChangeText` delegate method to get the current state of the input field. Using the `text` parameter of the aforementioned method, you can filter a view.

(Please correct me if I’m wrong — that’s how I think the app was implemented.)

**Comment by ayanonagon** [comment]
Auto-complete is a little out of scope for `VENTokenField`, but as @davidbarsky suggested, you can hook into the `tokenField:didChangeText:` method if you implement your own autocomplete form. :octocat:
