### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by cragworks** [venmo/VENTokenField#87]
1) Is there source code/how to for the UITableView like selection that pops up when typing a name into the VENTokenField?

2) How do you submit multiple recipients using the VENMO api in objective-c for iOS?

Thanks,
Calvin

**Comment by dasmer** [comment]
@cragworks 

1) There is no sample code or guide that demonstrates how the `UITableView` works for when typing in a name. In `VENTokenFieldDelegate`'s `didEnterText` you could show or hide a tableview based on the text string.

2) Currently the API does not support submitting multiple recipients. You would need to post a separate network request for each recipient.

Hope that's of some help. Good luck! :octocat:
